//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorInfo
    {
        public long Id { get; set; }
        public string Source { get; set; }
        public string Message { get; set; }
        public string InnerException { get; set; }
        public string Caller { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string StackTrace { get; set; }
        public string RequestURI { get; set; }
    }
}
