//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepairTracker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportStatusChangeLog
    {
        public int LogId { get; set; }
        public int RepairId { get; set; }
        public int StatusId { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual RepairStatusMaster RepairStatusMaster { get; set; }
        public virtual RepairTracker RepairTracker { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
