//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepairTracker.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RMSDbEntities : DbContext
    {
        public RMSDbEntities()
            : base("name=RMSDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RepairStatusMaster> RepairStatusMasters { get; set; }
        public virtual DbSet<RepairTracker> RepairTrackers { get; set; }
        public virtual DbSet<ReportStatusChangeLog> ReportStatusChangeLogs { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
    }
}
